version: '3.7'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 8080:8080
volumes:
  jenkins-data:
